language: 
 - c

compiler:
  - gcc

env:
 matrix:
  - TEST=python-api TYPE=unittest
  - TEST=python-api TYPE=integration
  - TEST=module TYPE=python
  - TEST=module TYPE=c

install:
 - wget -q -O- https://raw.githubusercontent.com/mithro/travis-trusty/master/setup.sh | bash
 - /trusty/run.sh bash $PWD/.travis-setup.sh

script:
 - /trusty/run.sh bash $PWD/.travis-run.sh

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"
